<?php
return [
    'app_name' => 'VMange',
    'base_url' => 'https://example.com/vbox',
    'force_https' => true,
    'db_host' => 'localhost',
    'db_name' => 'vmange',
    'db_user' => 'vmange',
    'db_pass' => 'change-me',
    // Uploaded releases must remain outside the web document root.
    'release_storage' => '',
    'setup_token' => 'replace-with-a-temporary-installer-token',
    'cookie_path' => '/vbox/',
    'online_window_seconds' => 120,
    'metrics_retention_hours' => 6,
    'cron_secret' => 'replace-with-a-long-random-cron-secret',
    'encryption_key' => 'replace-with-a-long-random-encryption-key',
    'webhook_url' => '',
    'webhook_secret' => '',
    'terminal_enabled' => false,
    'rate_limit_window' => 60,
    'rate_limit_max' => 90,
    'mail_from' => '',
    'mail_transport' => 'smtp',
    'smtp_host' => '',
    'smtp_port' => 587,
    'smtp_username' => '',
    'smtp_password' => '',
    'smtp_encryption' => 'tls',
    'imap_host' => '',
    'imap_port' => 993,
    'imap_username' => '',
    'imap_password' => '',
    'imap_encryption' => 'ssl',
];
