<?php
return [
    'app_name' => 'VMange',
    'base_url' => 'https://example.com/vbox',
    'force_https' => true,
    'db_host' => 'localhost',
    'db_name' => 'vmange',
    'db_user' => 'vmange',
    'db_pass' => 'change-me',
    'legacy_agent_token' => 'replace-with-a-long-random-token',
    'setup_token' => 'replace-with-a-temporary-installer-token',
    'cookie_path' => '/vbox/',
    'online_window_seconds' => 120,
    'rate_limit_window' => 60,
    'rate_limit_max' => 90,
    'mail_from' => '',
    'smtp_host' => '',
    'smtp_port' => 587,
    'smtp_username' => '',
    'smtp_password' => '',
    'smtp_encryption' => 'tls',
    'imap_host' => '',
    'imap_port' => 993,
    'imap_username' => '',
    'imap_password' => '',
    'imap_encryption' => 'ssl',
];
